name: make CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-full
            latexindent

      - name: make
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Khôlles_Mathématiques
          path: Khôlles_Mathématiques.pdf
