name: make CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-full
            latexindent

      - name: make
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Khôlles_Mathématiques
          path: Khôlles_Mathématiques.pdf

      - name: Upload individual PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Khôlles_Semaines
          path: Sem_*/Kholle_S*.pdf

      - name: Commit and push built files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Khôlles_Mathématiques.pdf
          git add Sem_*/Kholle_S*.pdf
          git commit -m "Action: add built files" || echo "No changes to commit"
          git push
